### ISSUE TITLE
Seems to be not compatible with CMS v9 LTS

### ISSUE THREAD

**Issue by kaystrobach** [NamelessCoder/typo3-cms-fluid-precompiler#7]
```
./vendor/bin/fluid-precompile -v -f
PHP Fatal error:  Class 'TYPO3\CMS\Backend\Console\Application' not found in /var/www/html/vendor/namelesscoder/typo3-cms-fluid-precompiler/src/ExternalApplication.php on line 18

Fatal error: Class 'TYPO3\CMS\Backend\Console\Application' not found in /var/www/html/vendor/namelesscoder/typo3-cms-fluid-precompiler/src/ExternalApplication.php on line 18
```

**Comment by NamelessCoder** [comment]
Hi @kaystrobach,

This repository contains the precompiler for just standalone Fluid - the one for TYPO3 CMS can be found at https://github.com/NamelessCoder/typo3-cms-fluid-precompiler-module and is dispatched via the normal TYPO3 CLI.

**Comment by kaystrobach** [comment]
🤦‍♂ also have the module installed, just have overseen the command controller - sry, thank you for your time.
